#!/bin/bash

TEXT="Locked"
FILE=/tmp/lockscreen.png

scrot --multidisp "$FILE"

convert "$FILE" \
    -quality 50% \
    -scale 10% \
    -scale 1000% \
    -fill black \
    -colorize 50% \
    "$FILE"

if [[ -f $1 ]]; then
    convert "$FILE" \
        "$1" -gravity center -composite -matte \
        "$FILE"
fi

i3lock -eui "$FILE"
rm "$FILE"
